/**
 * Per-blueprint location metadata sourced from the ARC Raiders community wiki.
 * Keyed by allowlist / trackerDisplayName (exact match).
 *
 * Source: https://arcraiders.wiki/wiki/Blueprints
 */

export type WikiBlueprintLocation = {
    /** Maps where this blueprint can be found. Empty means N/A (quest/trials only). */
    maps: string[]
    /** Required map conditions. Empty means any condition works. */
    conditions: string[]
    /** Container types that can contain this blueprint. */
    containers: string[]
    /** Quest name that rewards this blueprint, or null. */
    questReward: string | null
    /** Whether this blueprint can drop as a Trials reward. */
    trialsReward: boolean
}

const WIKI_LOCATIONS: Readonly<Record<string, WikiBlueprintLocation>> = {
    'Angled Grip II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Angled Grip III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Aphelion Rifle': {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: false,
    },
    Anvil: {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Barricade Kit': {
        maps: ['All'],
        conditions: [],
        containers: ['Electrical'],
        questReward: null,
        trialsReward: true,
    },
    Bettina: {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Blaze Grenade': {
        maps: ['All'],
        conditions: [],
        containers: ['Industrial'],
        questReward: null,
        trialsReward: true,
    },
    'Blue Light Stick': {
        maps: ['All'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    Bobcat: {
        maps: ['All'],
        conditions: ['Locked Gate (Hurricane)'],
        containers: ['Any', 'First Wave Cache'],
        questReward: null,
        trialsReward: true,
    },
    Burletta: {
        maps: [],
        conditions: [],
        containers: [],
        questReward: 'Industrial Espionage',
        trialsReward: true,
    },
    'Combat Mk. 3 (Aggressive)': {
        maps: ['Stella Montis', 'Blue Gate'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Combat Mk. 3 (Flanking)': {
        maps: ['Stella Montis', 'Blue Gate'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Compensator II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Compensator III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Complex Gun Parts': {
        maps: ['All'],
        conditions: [],
        containers: ['Security'],
        questReward: null,
        trialsReward: true,
    },
    Deadline: {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    Defibrillator: {
        maps: ['All'],
        conditions: [],
        containers: ['Medical'],
        questReward: null,
        trialsReward: true,
    },
    "El' Toro": {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    Equalizer: {
        maps: ['All'],
        conditions: ['Harvester'],
        containers: ['Harvester'],
        questReward: null,
        trialsReward: false,
    },
    'Explosive Mine': {
        maps: ['All'],
        conditions: [],
        containers: ['Industrial'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Barrel': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Light Mag II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Light Mag III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Medium Mag II': {
        maps: ['All'],
        conditions: ['Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Medium Mag III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Shotgun Mag II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Extended Shotgun Mag III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Firework Box': {
        maps: ['All'],
        conditions: ['Cold Snap'],
        containers: ['Any'],
        questReward: null,
        trialsReward: false,
    },
    'Gas Mine': {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: false,
    },
    'Green Light Stick': {
        maps: ['All'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    'Heavy Gun Parts': {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    Hullcracker: {
        maps: [],
        conditions: [],
        containers: [],
        questReward: "The Major's Footlocker",
        trialsReward: false,
    },
    'Jolt Mine': {
        maps: ['All'],
        conditions: [],
        containers: ['Industrial'],
        questReward: null,
        trialsReward: true,
    },
    Jupitar: {
        maps: ['All'],
        conditions: ['Harvester'],
        containers: ['Harvester'],
        questReward: null,
        trialsReward: false,
    },
    'Light Gun Parts': {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Lightweight Stock': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Looting Mk. 3 (Safekeeper)': {
        maps: ['All'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Looting Mk. 3 (Survivor)': {
        maps: ['All'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Lure Grenade': {
        maps: [],
        conditions: [],
        containers: [],
        questReward: 'Greasing Her Palms',
        trialsReward: false,
    },
    'Medium Gun Parts': {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Muzzle Brake II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Muzzle Brake III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    Osprey: {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Padded Stock': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Pulse Mine': {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    'Red Light Stick': {
        maps: ['All'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    'Remote Raider Flare': {
        maps: ['All'],
        conditions: [],
        containers: ['Electrical'],
        questReward: null,
        trialsReward: true,
    },
    'Seeker Grenade': {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: false,
    },
    'Shotgun Choke II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Shotgun Choke III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Shotgun Silencer': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid', 'Hidden Bunker'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    Showstopper: {
        maps: ['All'],
        conditions: [],
        containers: ['Industrial'],
        questReward: null,
        trialsReward: true,
    },
    'Silencer I': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Silencer II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Smoke Grenade': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Snap Hook': {
        maps: ['All'],
        conditions: ['EM Storm'],
        containers: ['Any'],
        questReward: null,
        trialsReward: false,
    },
    'Stable Stock II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Stable Stock III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Tactical Mk. 3 (Defensive)': {
        maps: ['Stella Montis', 'Blue Gate'],
        conditions: [],
        containers: ['Medical', 'Security', 'ARC Surveyor'],
        questReward: null,
        trialsReward: true,
    },
    'Tactical Mk. 3 (Healing)': {
        maps: ['Stella Montis', 'Blue Gate'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Tactical Mk. 3 (Revival)': {
        maps: ['Stella Montis', 'Blue Gate'],
        conditions: [],
        containers: ['Medical', 'Security'],
        questReward: null,
        trialsReward: true,
    },
    'Tagging Grenade': {
        maps: ['All'],
        conditions: [],
        containers: ['Electrical'],
        questReward: null,
        trialsReward: true,
    },
    Tempest: {
        maps: ['All'],
        conditions: ['Night Raid (Hurricane)'],
        containers: ['Residential', 'First Wave Cache'],
        questReward: null,
        trialsReward: true,
    },
    Torrentte: {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Trailblazer Grenade': {
        maps: ['Stella Montis'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
    'Trigger Nade': {
        maps: ['All'],
        conditions: [],
        containers: ['Any'],
        questReward: 'Sparks Fly',
        trialsReward: false,
    },
    Venator: {
        maps: ['All'],
        conditions: [],
        containers: ['Raider'],
        questReward: null,
        trialsReward: true,
    },
    'Vertical Grip II': {
        maps: ['All'],
        conditions: [],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Vertical Grip III': {
        maps: ['All'],
        conditions: ['EM Storm', 'Locked Gate', 'Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Vita Shot': {
        maps: ['All'],
        conditions: [],
        containers: ['Medical', 'ARC Surveyor'],
        questReward: null,
        trialsReward: true,
    },
    'Vita Spray': {
        maps: ['All'],
        conditions: [],
        containers: ['Medical', 'ARC Surveyor'],
        questReward: 'Worth Your Salt',
        trialsReward: true,
    },
    Vulcano: {
        maps: ['All'],
        conditions: ['Hidden Bunker (Hurricane)'],
        containers: ['Any', 'First Wave Cache'],
        questReward: null,
        trialsReward: true,
    },
    Wolfpack: {
        maps: ['All'],
        conditions: ['Night Raid'],
        containers: ['Residential'],
        questReward: null,
        trialsReward: true,
    },
    'Yellow Light Stick': {
        maps: ['All'],
        conditions: [],
        containers: ['Any'],
        questReward: null,
        trialsReward: true,
    },
}

/**
 * Returns wiki location data for a blueprint by its trackerDisplayName / allowlist label.
 * Returns null if no data is available for the given name.
 */
export function getWikiBlueprintLocation(trackerDisplayName: string | null | undefined): WikiBlueprintLocation | null {
    if (!trackerDisplayName) return null
    return WIKI_LOCATIONS[trackerDisplayName.trim()] ?? null
}
